CREATE TABLE IF NOT EXISTS plot_level_derived_indices (
  site_unique VARCHAR (50) PRIMARY KEY UNIQUE NOT NULL,
  site_location_id SERIAL NOT NULL,
  site_location_visit_id SERIAL NOT NULL,
  richness decimal,
  rrr decimal,
  cwe decimal,
  richness_native decimal,
  rrr_native decimal,
  cwe_native decimal,
  richness_alien decimal,
  rrr_alien decimal,
  cwe_alien decimal,
  shannon decimal,
  simpson decimal,
  shannon_native decimal,
  simpson_native decimal,
  shannon_alien decimal,
  simpson_alien decimal,
  height_cwm decimal,
  leaf_cwm decimal,
  seed_cwm decimal,
  leaf_mass_per_area_cwm decimal,
  sla_cwm decimal,
  height_cwv decimal,
  leaf_cwv decimal,
  seed_cwv decimal,
  leaf_mass_per_area_cwv decimal,
  sla_cwv decimal,
  hv_svm_nolog decimal,
  lognormal decimal,
  coverage_pct_native decimal,
  cwm_bio1_98_native decimal,
  cwm_bio12_02_native decimal,
  species_richness_pi decimal,
  functional_diversity_pi decimal,
  rao_quadratic_diversity_pi decimal,
  functional_uniqueness_pi decimal,
  functional_redundancy_pi decimal,
  CONSTRAINT fk_site_location_visit_id FOREIGN KEY (site_location_visit_id) REFERENCES site_location_visit (site_location_visit_id),
  CONSTRAINT fk_site_location_id FOREIGN KEY (site_location_id) REFERENCES site_location (site_location_id)
)